#!/usr/bin/env python
# SCsub
#
# Copyright © Noé Perard-Gayot 2021.                                                                                        #
# Licensed under the MIT License. You may obtain a copy of the License at https://opensource.org/licenses/mit-license.php   #
#
#!/usr/bin/env python

Import("env")
Import("env_modules")

env_utility_ai = env_modules.Clone()

# Thirdparty source files
# Godot source files

module_obj = []

env_utility_ai.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj
